### ISSUE TITLE
Issue when running on CPU : "TypeError : iteration over a 0-d array " in model.py

### ISSUE THREAD

**Issue by leo-p-labs** [wenhuchen/Table-Fact-Checking#11]
I'm running `python model.py --do_train --do_val --batch_size 2` with `torch.device('cpu')`

Here is the error message :
```
Traceback (most recent call last):
  File "model.py", line 257, in <module>
    precision, recall, accuracy = evaluate(val_dataloader, encoder_stat, encoder_prog)
  File "model.py", line 142, in evaluate
    for i, s, p, t, inp_id, prog_id in zip(index, similarity, pred_lab, true_lab, input_ids, prog_ids):
TypeError: iteration over a 0-d array
```

My configuration is the following :
ubuntu 20.04
python 3.8.1 (installed with pyenv)

python packages :
boto3==1.17.55
botocore==1.20.55
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
idna==2.10
jmespath==0.10.0
joblib==1.0.1
nltk==3.6.2
numpy==1.20.2
pandas==1.2.4
protobuf==3.15.8
python-dateutil==2.8.1
pytorch-pretrained-bert==0.6.2
pytz==2021.1
regex==2021.4.4
requests==2.25.1
s3transfer==0.4.1
six==1.15.0
tdqm==0.0.1
tensorboardX==2.2
torch==1.8.1+cpu
tqdm==4.60.0
typing-extensions==3.7.4.3
ujson==1.35
Unidecode==1.2.0
urllib3==1.26.4

**Comment by wenhuchen** [comment]
Hi there, thanks for your interest in my code. I haven't exactly worked on CPU training. This bug might lead to pytorch library, not quite solvable from my side. But I can definitely provide some suggestions.

From my observation, it seems that one of "index, similarity, pred_lab, true_lab, input_ids, prog_ids" only has zero-dimension. I feel that "pred_lab, true_lab" are calculated by GPU device, these could be somewhat miscalculated under CPU environment. Could you identify which are the cause of failure and try to see how is caused by CPU?

**Comment by leo-p-labs** [comment]
Hi thanks for your help, i'm searching actually, when i'll find it i'll come back to you.
