### ISSUE TITLE
Not really an issue, but a question

### ISSUE THREAD

**Issue by Rahul-Khanna** [wenhuchen/Table-Fact-Checking#2]
Hey Wenhu, was wondering if you could shed some light on the batch size you used in training. Was it the default 6? I'm trying to replicate your paper results, but using your saved model I can't quite get the results you got in your paper. I know you are using 16 as the batch size in evaluation, so was wondering if maybe that was the same for training? Trying to replicate your fact first, template table bert results.

 I actually just emailed, you as well :)

**Comment by wenhuchen** [comment]
Hi Rahul,

Thanks a lot for your interest in my dataset. The number reported in the paper is average over multiple runs, let me re-check about the s3's model. For the training, I was using a batch size of 6 due to memory constraints. I didn't try other settings, but I would expect the model to achieve roughly the same result. The peak accuracy seems to be quite stable across different settings from my experience.

Bests,

**Comment by Rahul-Khanna** [comment]
Thanks man, saw your email!
